## Tensor

텐서는 배열(array)이나 행렬(matrix)과 매우 유사한 특수 자료구조로, PyTorch에서는 텐서를 사용하여 모델의 입력과 출력뿐만 아니라 모델의 매개변수를 encode하기도 한다.

In [10]:
import platform

In [11]:
import torch
import numpy as np

### Tensor 초기화

In [4]:
# 1) 데이터로부터 바로 생성
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [5]:
# 2) NumPy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
# 3) 다른 텐서로부터 생성: 명시적으로 override 하지 않는다면 인자로 주어진 텐서의 shape, datatype 유지
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) # dtype override
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8932, 0.1250],
        [0.5831, 0.3959]])


In [7]:
# 4) 무작위 또는 상수 값 사용
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.4312, 0.1350, 0.5537],
        [0.7755, 0.1786, 0.4219]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성(attribute)

텐서의 속성(attribute)이란 shape, datatype, 그리고 어느 장치에 해당 텐서가 저장되는지를 나타낸다

In [9]:
tensor = torch.rand(3,4)
print(f'{tensor.shape = }')
print(f'{tensor.dtype = }')
print(f'{tensor.device = }')

tensor.shape = torch.Size([3, 4])
tensor.dtype = torch.float32
tensor.device = device(type='cpu')


### 텐서 연산(operation)

transposing, indexing, slicing, 수학 계산, 선형 대수, random sampling 등

In [17]:
# GPU Setting
if platform.system() == 'Darwin': # MacOS
    if torch.backends.mps.is_built() and torch.backends.mps.is_available():
        # device = torch.device("mps")
        tensor = tensor.to('mps')
elif torch.cuda.is_available():
    tensor = tensor.to('cuda')

print(f'{tensor.device = }')

tensor.device = device(type='mps', index=0)


In [18]:
# TBD

### NumPy 변환 (Bridge)

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유한다 == 하나를 변경하면 다른 하나도 변경된다!

In [27]:
t = torch.ones(5)
print(f'{t = }')

n = t.numpy()
print(f'{n = }')

t = tensor([1., 1., 1., 1., 1.])
n = array([1., 1., 1., 1., 1.], dtype=float32)


In [28]:
t.add_(1)
print(f'{t = }')
print(f'{n = }')

t = tensor([2., 2., 2., 2., 2.])
n = array([2., 2., 2., 2., 2.], dtype=float32)


In [29]:
n = np.ones(5)
t = torch.from_numpy(n)

In [30]:
np.add(n, 2, out=n)
print(f'{t = }')
print(f'{n = }')

t = tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n = array([3., 3., 3., 3., 3.])
